### ISSUE TITLE
Segfault from my_2D_fft_complex

### ISSUE THREAD

**Issue by olivierhenaff** [edouardoyallon/scatwave#14]
Good morning!

I tried running the minimal example:

scatwave = require 'scatwave'
x=torch.FloatTensor(128,3,32,32)
scat = scatwave.network.new(3,x:size())

but unfortunately I get a segfault at the last line. I tracked down the problem, and found that it was happening when this function calls 

filters_bank.morlet_filters_bank_2D(U0_dim,J,self.fft) (line 28 of network_2d_translation.lua)

and that the problem with this function is performing 

fft.my_2D_fft_complex(psi) (line 114 of filters_bank.lua)

Sure enough, you mention that the following line

fftw.C['fftwf_execute'](plan) (line 163 of wrapper_fft.lua)

can cause a segfault. Is there a way to make it not segfault? 

Thanks a bunch for your time,

Olivier

**Comment by edouardoyallon** [comment]
Hi!

I guess there is an issue with the setup of fftw.. You will have to check the wrapper..

However, this is unfortunately an obsolete version of the scattering transform. Please switch to the pytorch version, which is quite more faster and simpler to use and understand, I will not maintain this package.. I let it here for legacy purpose. 

https://github.com/edouardoyallon/pyscatwave

Thanks

Best,
EO

**Comment by olivierhenaff** [comment]
Great, I'll look into that. 

Thanks a bunch!

Olivier
